readthedocs/urls.py
from django.conf.urls.defaults import url, patterns, include
from django.contrib import admin
from django.conf import settings
from django.views.generic.simple import direct_to_template

from tastypie.api import Api
from rest_framework import routers

from api.base import (ProjectResource, UserResource, BuildResource,
                      VersionResource, FileResource)
from builds.filters import VersionFilter
from core.forms import UserProfileForm
from core.views import SearchView
from projects.feeds import LatestProjectsFeed, NewProjectsFeed
from projects.filters import ProjectFilter
from projects.constants import LANGUAGES_REGEX
from restapi.views import ProjectViewSet, NotificationViewSet


v1_api = Api(api_name='v1')
v1_api.register(BuildResource())
v1_api.register(UserResource())
v1_api.register(ProjectResource())
v1_api.register(VersionResource())
v1_api.register(FileResource())

# API v2
router = routers.DefaultRouter()
router.register(r'project', ProjectViewSet)
router.register(r'notification', NotificationViewSet)

admin.autodiscover()

handler500 = 'core.views.server_error'
handler404 = 'core.views.server_error_404'

urlpatterns = patterns(
    '',  # base view, flake8 complains if it is on the previous line.
    url(r'^$', 'core.views.homepage'),
    url(r'^security/', direct_to_template, {'template': 'security.html'}),

    # For serving docs locally and when nginx isn't
    url((r'^docs/(?P<project_slug>[-\w]+)/(?P<lang_slug>%s)/(?P<version_slug>'
         r'[-._\w]+?)/(?P<filename>.*)$') % LANGUAGES_REGEX,
        'core.views.serve_docs',
        name='docs_detail'),

    # Redirect to default version.
    url(r'^docs/(?P<project_slug>[-\w]+)/$',
        'core.views.serve_docs',
        {
            'version_slug': None,
            'lang_slug': None,
            'filename': '',
        },
        name='docs_detail'),

    # Handle /page/<path> redirects for explicit "latest" version goodness.
    url(r'^docs/(?P<project_slug>[-\w]+)/page/(?P<filename>.*)$',
        'core.views.serve_docs',
        {
            'version_slug': None,
            'lang_slug': None,
        },
        name='docs_detail'),

    url(r'^projects/', include('projects.urls.public')),
    url(r'^builds/', include('builds.urls')),
    url(r'^flagging/', include('basic.flagging.urls')),
    url(r'^accounts/', include('registration.backends.default.urls')),
    url(r'^search/project/', SearchView.as_view(), name='haystack_project'),
    url(r'^search/', include('haystack.urls')),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^dashboard/', include('projects.urls.private')),
    url(r'^github', 'core.views.github_build', name='github_build'),
    url(r'^bitbucket', 'core.views.bitbucket_build', name='bitbucket_build'),
    url(r'^build/(?P<pk>\d+)',
        'core.views.generic_build',
        name='generic_build'),
    url(r'^random/(?P<project>[\w-]+)',
        'core.views.random_page',
        name='random_page'),
    url(r'^random/$', 'core.views.random_page', name='random_page'),
    url(r'^depth/$', 'core.views.queue_depth', name='queue_depth'),
    url(r'^live/$', 'core.views.live_builds', name='live_builds'),
    url(r'^500/$', 'core.views.divide_by_zero', name='divide_by_zero'),
    url(r'^filter/version/$',
        'django_filters.views.object_filter',
        {'filter_class': VersionFilter, 'template_name': 'filter.html'},
        name='filter_version'),
    url(r'^filter/project/$',
        'django_filters.views.object_filter',
        {'filter_class': ProjectFilter, 'template_name': 'filter.html'},
        name='filter_project'),
    url(r'^wipe/(?P<project_slug>[-\w]+)/(?P<version_slug>[\w]{1}[-\w\.]+)/$',
        'core.views.wipe_version',
        name='wipe_version'),
    url(r'^profiles/create/', 'profiles.views.create_profile',
        {'form_class': UserProfileForm},
        name='profiles_profile_create'),
    url(r'^profiles/edit/', 'profiles.views.edit_profile',
        {'form_class': UserProfileForm},
        name='profiles_profile_edit'),
    url(r'^profiles/', include('profiles.urls')),
    url(r'^api/', include(v1_api.urls)),
    url(r'^api/v2/', include(router.urls)),
    url(r'^api-auth/', include('rest_framework.urls', namespace='rest_framework')),
    url(r'^feeds/new/$',
        NewProjectsFeed(),
        name="new_feed"),
    url(r'^feeds/latest/$',
        LatestProjectsFeed(),
        name="latest_feed"),
    url(r'^mlt/(?P<project_slug>[-\w]+)/(?P<filename>.*)$',
        'core.views.morelikethis',
        name='morelikethis'),
    url(r'^websupport/', include('websupport.urls')),

)

if settings.DEBUG:
    urlpatterns += patterns(
        '',  # base view, flake8 complains if it is on the previous line.
        url('style-catalog/$',
            'django.views.generic.simple.direct_to_template',
            {'template': 'style_catalog.html'}),
        url(regex='^%s/(?P<path>.*)$' % settings.MEDIA_URL.strip('/'),
            view='django.views.static.serve',
            kwargs={'document_root': settings.MEDIA_ROOT}),
    )

readthedocs/builds/models.py
from django.db import models
from django.utils.translation import ugettext_lazy as _, ugettext

from guardian.shortcuts import assign, get_objects_for_user
from taggit.managers import TaggableManager

from projects.models import Project
from projects import constants
from .constants import BUILD_STATE, BUILD_TYPES


class VersionManager(models.Manager):
    def _filter_queryset(self, user, project, privacy_level, only_active):
        if isinstance(privacy_level, basestring):
            privacy_level = (privacy_level,)
        queryset = Version.objects.filter(privacy_level__in=privacy_level)
        # Remove this so we can use public() for all active public projects
        #if not user and not project:
            #return queryset
        if user and user.is_authenticated():
            # Add in possible user-specific views
            user_queryset = get_objects_for_user(user, 'builds.view_version')
            queryset = user_queryset | queryset
        elif user:
            # Hack around get_objects_for_user not supporting global perms
            global_access = user.has_perm('builds.view_version')
            if global_access:
                queryset = Version.objects.all()
        if project:
            # Filter by project if requested
            queryset = queryset.filter(project=project)
        if only_active:
            queryset = queryset.filter(active=True)
        return queryset

    def active(self, user=None, project=None, *args, **kwargs):
        queryset = self._filter_queryset(
            user,
            project,
            privacy_level=(constants.PUBLIC, constants.PROTECTED,
                           constants.PRIVATE),
            only_active=True,
        )
        return queryset.filter(*args, **kwargs)

    def public(self, user=None, project=None, only_active=True, *args,
               **kwargs):
        queryset = self._filter_queryset(
            user,
            project,
            privacy_level=(constants.PUBLIC),
            only_active=only_active
        )
        return queryset.filter(*args, **kwargs)

    def protected(self, user=None, project=None, only_active=True, *args,
                  **kwargs):
        queryset = self._filter_queryset(
            user,
            project,
            privacy_level=(constants.PUBLIC, constants.PROTECTED),
            only_active=only_active
        )
        return queryset.filter(*args, **kwargs)

    def private(self, user=None, project=None, only_active=True, *args,
                **kwargs):
        queryset = self._filter_queryset(
            user,
            project,
            privacy_level=(constants.PRIVATE),
            only_active=only_active
        )
        return queryset.filter(*args, **kwargs)


class Version(models.Model):
    project = models.ForeignKey(Project, verbose_name=_('Project'),
                                related_name='versions')
    # used by the vcs backend
    identifier = models.CharField(_('Identifier'), max_length=255)

    verbose_name = models.CharField(_('Verbose Name'), max_length=255)
    slug = models.CharField(_('Slug'), max_length=255)
    active = models.BooleanField(_('Active'), default=False)
    built = models.BooleanField(_('Built'), default=False)
    uploaded = models.BooleanField(_('Uploaded'), default=False)
    privacy_level = models.CharField(
        _('Privacy Level'), max_length=20, choices=constants.PRIVACY_CHOICES,
        default='public', help_text=_("Level of privacy for this Version."))

    tags = TaggableManager(blank=True)
    objects = VersionManager()

    class Meta:
        unique_together = [('project', 'slug')]
        ordering = ['-verbose_name']
        permissions = (
            # Translators: Permission around whether a user can view the
            #              version
            ('view_version', _('View Version')),
        )

    def __unicode__(self):
        return ugettext(u"Version %(version)s of %(project)s (%(pk)s)" % {
            'version': self.verbose_name,
            'project': self.project,
            'pk': self.pk
        })

    def get_absolute_url(self):
        if not self.built and not self.uploaded:
            return ''
        return self.project.get_docs_url(version_slug=self.slug)

    def save(self, *args, **kwargs):
        """
        Add permissions to the Version for all owners on save.
        """
        obj = super(Version, self).save(*args, **kwargs)
        for owner in self.project.users.all():
            assign('view_version', owner, self)
        return obj


class VersionAlias(models.Model):
    project = models.ForeignKey(Project, verbose_name=_('Project'),
                                related_name='aliases')
    from_slug = models.CharField(_('From slug'), max_length=255, default='')
    to_slug = models.CharField(_('To slug'), max_length=255, default='',
                               blank=True)
    largest = models.BooleanField(_('Largest'), default=False)

    def __unicode__(self):
        return ugettext(u"Alias for %(project)s: %(from)s -> %(to)s" % {
            'project': self.project,
            'form': self.from_slug,
            'to': self.to_slug,
        })


class Build(models.Model):
    project = models.ForeignKey(Project, verbose_name=_('Project'),
                                related_name='builds')
    version = models.ForeignKey(Version, verbose_name=_('Version'), null=True,
                                related_name='builds')
    type = models.CharField(_('Type'), max_length=55, choices=BUILD_TYPES,
                            default='html')
    state = models.CharField(_('State'), max_length=55, choices=BUILD_STATE,
                             default='finished')
    date = models.DateTimeField(_('Date'), auto_now_add=True)
    success = models.BooleanField(_('Success'))
    setup = models.TextField(_('Setup'), null=True, blank=True)
    setup_error = models.TextField(_('Setup error'), null=True, blank=True)
    output = models.TextField(_('Output'), default='', blank=True)
    error = models.TextField(_('Error'), default='', blank=True)

    class Meta:
        ordering = ['-date']
        get_latest_by = 'date'

    def __unicode__(self):
        return ugettext(u"Build %(project)s for %(usernames)s (%(pk)s)" % {
            'project': self.project,
            'usernames': ' '.join(self.project.users.all()
                                  .values_list('username', flat=True)),
            'pk': self.pk,
        })

    @models.permalink
    def get_absolute_url(self):
        return ('builds_detail', [self.project.slug, self.pk])

readthedocs/core/models.py
from django.db import models
from django.db.models.signals import post_save
from django.db.utils import DatabaseError
from django.dispatch import receiver
from django.contrib.auth.models import User
from django.utils.translation import ugettext_lazy as _, ugettext

STANDARD_EMAIL = "anonymous@readthedocs.org"


class UserProfile (models.Model):
    """Additional information about a User.
    """
    user = models.ForeignKey(User, verbose_name=_('User'), unique=True,
                             related_name='profile')
    whitelisted = models.BooleanField(_('Whitelisted'))
    homepage = models.CharField(_('Homepage'), max_length=100, blank=True)
    allow_email = models.BooleanField(_('Allow email'),
                                      help_text=_('Show your email on VCS '
                                                  'contributions.'),
                                      default=True)

    def __unicode__(self):
        return (ugettext("%(username)s's profile")
                % {'username': self.user.username})

    def get_form(self):
        from .forms import UserProfileForm
        return UserProfileForm(instance=self)

    def get_absolute_url(self):
        return ('profiles_profile_detail', (),
                {'username': self.user.username})

    get_absolute_url = models.permalink(get_absolute_url)

    def get_contribution_details(self):
        """
        Gets the line to put into commits to attribute the author.

        Returns a tuple (name, email)
        """
        if self.user.first_name and self.user.last_name:
            name = '%s %s' % (self.user.first_name, self.user.last_name)
        else:
            name = self.user.username
        if self.allow_email:
            email = self.user.email
        else:
            email = STANDARD_EMAIL
        return (name, email)


@receiver(post_save, sender=User)
def create_profile(sender, **kwargs):
    if kwargs['created'] is True:
        try:
            UserProfile.objects.create(user_id=kwargs['instance'].id)
        except DatabaseError:
            pass

readthedocs/core/forms.py
import logging
from haystack.forms import SearchForm
from haystack.query import SearchQuerySet

from django import forms
from django.forms.fields import CharField
from django.utils.translation import ugettext_lazy as _
from models import UserProfile

log = logging.getLogger(__name__)


class UserProfileForm(forms.ModelForm):
    first_name = CharField(label=_('First name'), required=False)
    last_name = CharField(label=_('Last name'), required=False)

    class Meta:
        model = UserProfile
        # Don't allow users edit someone else's user page,
        exclude = ('user', 'whitelisted')

    def __init__(self, *args, **kwargs):
        super(UserProfileForm, self).__init__(*args, **kwargs)
        try:
            self.fields['first_name'].initial = self.instance.user.first_name
            self.fields['last_name'].initial = self.instance.user.last_name
        except:
            pass

    def save(self, *args, **kwargs):
        first_name = self.cleaned_data.pop('first_name', None)
        last_name = self.cleaned_data.pop('last_name', None)
        profile = super(UserProfileForm, self).save(*args, **kwargs)
        if kwargs.get('commit', True):
            user = profile.user
            user.first_name = first_name
            user.last_name = last_name
            user.save()
        return profile


class FacetField(forms.MultipleChoiceField):
    '''
    For filtering searches on a facet, with validation for the format
    of facet values.
    '''
    def valid_value(self, value):
        '''
        Although this is a choice field, no choices need to be supplied.
        Instead, we just validate that the value is in the correct format
        for facet filtering (facet_name:value)
        '''
        if ":" not in value:
            return False
        return True


class FacetedSearchForm(SearchForm):
    '''
    Supports fetching faceted results with a corresponding query.

    `facets`
        A list of facet names for which to get facet counts
    `models`
        Limit the search to one or more models
    '''

    selected_facets = FacetField(required=False)

    def __init__(self, *args, **kwargs):
        facets = kwargs.pop('facets', [])
        models = kwargs.pop('models', [])
        super(FacetedSearchForm, self).__init__(*args, **kwargs)

        for facet in facets:
            self.searchqueryset = self.searchqueryset.facet(facet)
        if models:
            self.searchqueryset = self.searchqueryset.models(*models)

    def clean_selected_facets(self):
        facets = self.cleaned_data['selected_facets']
        cleaned_facets = []
        clean = SearchQuerySet().query.clean
        for facet in facets:
            field, value = facet.split(":", 1)
            if not value:  # Ignore empty values
                continue
            value = clean(value)
            cleaned_facets.append(u'%s:"%s"' % (field, value))
        return cleaned_facets

    def search(self):
        sqs = super(FacetedSearchForm, self).search()
        for facet in self.cleaned_data['selected_facets']:
            sqs = sqs.narrow(facet)
        self.searchqueryset = sqs
        return sqs

readthedocs/templates/core/bookmark_list_detailed.html
{% for bookmark in bookmark_list %}
  <li class="module-item">
    <a class="module-item-title" href="{{ bookmark.get_absolute_url }}">{{ bookmark.url }}</a>
    <a href="{% url projects_user_list bookmark.user.username %}" class="quiet">({{ bookmark.user }})</a>
    <span class="quiet">{% if bookmark.project.version %}version {{ bookmark.project.version }} -{% endif %} {{ bookmark.date|timesince }} ago</span>
  </li>
{% endfor %}

readthedocs/templates/core/build_list_detailed.html
{% load i18n %}

          {% for build in build_list %}
          <li class="module-item col-span">
            <div id="build-{{ build.id }}">
                <a href="{{ build.get_absolute_url }}"><span id="build-state">{% if build.state != 'finished' %}{{ build.get_state_display }} {% else %} {% if build.success %}{% trans "Passed" %}{% else %}{% trans "Failed" %}{% endif %}{% endif %}</span>
              <img src="{{ MEDIA_URL }}images/loader.gif" class="build-loading hide">
              <span class="quiet">{% if build.version %}{% blocktrans with build.version.slug as slug and build.type as type %}version {{ slug }} ({{ type }}){% endblocktrans %}{% endif %}</span><span class="quiet right">{% blocktrans with build.date|timesince as date %}{{ date }} ago{% endblocktrans %}</span>
              </a>
            </div>
            </li>
          {% empty %}
            <li class="module-item quiet">{% trans "No builds found" %}</li>
          {% endfor %}

readthedocs/templates/core/filter_bar.html
{% load i18n %}

    <!-- BEGIN project bar -->
    <div id="project_bar">
      <div class="wrapper">

        <div class="project-title">
          <h1>{% trans "Filter" %}</h1>
        </div>

        <div class="options">


          <ul>
            {% block filter_bar %}{% endblock %}
          </ul>
        </div>


      </div>
    </div>
    <!-- END project bar -->

readthedocs/templates/core/filter_list.html
{% load i18n %}

        {% for obj in filter %}
        <li class="module-item col-span">
            <div id="obj-{{ obj.id }}">
                <a href="{{ obj.get_absolute_url }}">
                    {{ obj }}
              </a>
            </div>
        </li>
        {% empty %}
        <li class="module-item quiet">{% trans "No objects found" %}</li>
        {% endfor %}

readthedocs/templates/core/header.html
{% load i18n %}

{% if include_render %}
    <!-- rtfd header style -->
    <link rel="stylesheet" href="{{ MEDIA_URL }}css/header.css">
    <!-- typekit -->
    <script type="text/javascript" src="http://use.typekit.com/xgl8ypn.js"></script>
    <script type="text/javascript">try{Typekit.load();}catch(e){}</script>
    <!-- jquery -->
    <!-- <script type="text/javascript" src="http://ajax.googleapis.com/ajax/libs/jquery/1.4/jquery.min.js"></script> -->
    <script type="text/javascript" src="http://ajax.googleapis.com/ajax/libs/jqueryui/1.8.4/jquery-ui.min.js"></script>
    <script type="text/javascript">
      $(function() {
        /*
        $('.rtfd-header-search input:text').autocomplete({
          source: '/projects/search/autocomplete/',
          minLength: 2,
          open: function(event, ui) {
            ac_top = $('.ui-autocomplete').css('top');
            $('.ui-autocomplete').css({'width': '233px', 'top': ac_top + 10 });
          }
        });
        */

        {% comment %}
        $('.rtfd-header-bookmark-icon').click(function(e) {
          e.preventDefault();
          link = $(this);
          add_url = '{% url bookmarks_add request.META.PATH_INFO %}';
          remove_url = '{% url bookmarks_remove request.META.PATH_INFO %}';
          $.ajax({
            url: link.attr('href'),
            dataType: 'json',
            success: function(data) {
              if (data['added']) {
                link.addClass('active');
                link.attr('href', remove_url);
              } else {
                link.removeClass('active');
                link.attr('href', add_url);
              }
            }
          });
        });
        {% endcomment %}
      });
    </script>
{% endif %}

    <!-- BEGIN header-->
    <div id="rtfd-header">
      <div class="wrapper">

        <!-- BEGIN header title-->
        <div class="rtfd-header-title">
            <h1>
                {% comment %}Translators: Name of the website{% endcomment %}
                <a href="{% url core.views.homepage %}">{% trans "Read the Docs" %}</a>
            </h1>
        </div>
        <!-- END header title -->

        <!-- BEGIN global search -->
        <div class="rtfd-header-search">
          <form action="{% url haystack_project %}" method="GET">
            <input type="text" name="q" value="{{ term }}" id="id_site_search">
            <input type="submit" value="{% trans "Go" %}">
          </form>
        </div>
        <!-- END global search -->

        {% comment %}
        {% if do_bookmarking and request.user.is_authenticated %}
        <!-- BEGIN bookmark -->
        {% if request.META.PATH_INFO != '/' %}
        <div class="rtfd-header-bookmark">
          {% if has_bookmark %}
            <a href="{% url bookmarks_remove request.META.PATH_INFO %}" class="rtfd-header-bookmark-icon active">{% trans "Remove bookmark" %}</a>
          {% else %}
            <a href="{% url bookmarks_add request.META.PATH_INFO %}" class="rtfd-header-bookmark-icon">{% trans "Bookmark this URL" %}</a>
          {% endif %}
        </div>
        {% endif %}
        <!-- END bookmark -->
        {% endif %}
        {% endcomment %}

        <!-- BEGIN header nav -->
        <div class="rtfd-header-nav">
          <ul>
            {% if request.user.is_authenticated %}
              <li class="{{ dashboard_active }}"><a href="{% url projects_dashboard %}">{% trans "Dashboard" %}</a></li>
              <li><a href="{% url auth_logout %}">{% trans "Log Out" %}</a></li>
            {% else %}
              <li><a href="{% url auth_login %}">{% trans "Log in" %}</a></li>
            {% endif %}


          </ul>
        </div>
        <!-- END header nav -->

      </div>
    </div>
    <!-- END header-->

readthedocs/templates/core/project_details.html
{% load i18n %}
{% load markup %}

{% if project.description %}
  <h3>{% trans "Description" %}</h3>
  <div id="project_description">
  <p>
    {{ project.description|restructuredtext }}
  </p>
  </div>
{% endif %}

<!-- BEGIN search bar -->
<div class="search">
  <form action="{% url haystack_project %}" method="GET">
    <input type="text" name="q" value="" placeholder="{% blocktrans %}Search {{ project }}{% endblocktrans %}" id="id_site_search">
    <input type="hidden" name="selected_facets" value="project_exact:{{ project.name }}">
    <input type="submit" value="{% trans "Search" %}">
  </form>
</div>
<br>
<!-- END search bar -->

{% if versions %}
<div class="module">
  <div class="module-header">
    <h3>{% trans "Versions" %}</h3>
  </div>

  <div class="module-list">

  {% comment %}
    <div class="filter_form">
      <form id="filter_form">
        {{ filter.form }}
        <input type="submit" value="{% trans "Filter" %}">
      </form>
    </div>
  {% endcomment %}

    <div class="module-list-wrapper">
      <ul>
      {% for version in filter %}
        <li class="module-item col-span">
        {% if version.uploaded or version.built %}
          {# Link to the docs #}
          <a class="module-item-title" href="{{ version.get_absolute_url }}">
            {% blocktrans with version.slug as slug %} {{ slug }} {% endblocktrans %}
          {% if request.user in project.users.all %}
            <span class="right-menu quiet">{{ version.get_privacy_level_display }}</span>
          {% endif %}
          </a>
        {% else %}
          <a class="module-item-title" href="{{ version.project.get_builds_url }}">
            {% blocktrans with version.slug as slug %} {{ slug }} (Build Failed){% endblocktrans %}
          </a>
        {% endif %}
          {% if request.user in project.users.all %}
            <ul class="module-item-menu">
              <li><a href="{% url project_version_detail project.slug version.slug %}">{% trans "Edit" %}</a></li>
            </ul>
          {% endif %}
        </li>
      {% endfor %}
      </ul>
    </div>
  </div>

  <div class="build_a_version">
    <h3>{% trans "Build a version" %}</h3>
    <div style="float: left; margin-right: 5px;" class="version_right">
      <form method="post" action="{% url generic_build project.pk %}">
        <select id="id_version" name="version_slug">
        {% for version in project.ordered_active_versions %}
          <option value="{{ version.slug }}">{{ version.slug }}</option>
        {% endfor %}
        </select>
        <input type="submit" value="{% trans "Build" %}">
      </form>
    </div>
  </div>
</div>{# END .module #}
{% endif %}

<div class="project_details">

  {% if project.repo %}
    <h3>{% trans "Repository" %}</h3>
    <p>{{ project.repo|urlize }}</p>
  {% endif %}

  {% if project.tags.count %}
    <h3>{% trans "Tags" %}</h3>
    <p>
      {% for tag in project.tags.all %}
        <a href="{% url projects_tag_detail tag.slug %}">{{ tag.name }}</a>{% if forloop.last %}{% else %}, {% endif %}
      {% empty %}
        <span class="quiet">{% trans "No tags" %}</span>
      {% endfor %}
    </p>
  {% endif %}

  <h3>{% trans "Last Built" %}</h3>
  <p>{{ project.modified_date|timesince }} ago</p>

  {% if project.project_url %}
    <h3>{% trans "Home Page" %}</h3>
    <p>
      <a href="{{ project.project_url }}" rel="nofollow,noindex">{{ project.project_url }}</a>
    </p>
  {% endif %}

  <h3>{% trans "Project Privacy Level" %}</h3>
  <div id="privacy_level">
    <p>
      {{ project.get_privacy_level_display }}
    </p>
  </div>

  <h3>{% trans "Short URLs" %}</h3>
  <p>
    <a href="//{{ project.slug}}.{{ PRODUCTION_DOMAIN }}">{{ project.slug }}.{{ PRODUCTION_DOMAIN }}</a><br>
    {% if PRODUCTION_DOMAIN == "readthedocs.org" %}
    <a href="//{{ project.slug}}.rtfd.org">{{ project.slug }}.rtfd.org</a>
    {% endif %}
  </p>

  {% if project.django_packages_url %}
  <h3>{% trans "Open Comparison" %}</h3>
  <p>{% blocktrans with project.django_packages_url as url %}This project has more information available about it on <a href="{{ url }}">Open Comparison!</a>{% endblocktrans %}</p>
  {% endif %}

  {% if project.crate_url %}
  <h3>{% trans "Crate" %}</h3>
  <p>{% blocktrans with project.crate_url as url %}This project has more information available about it on <a href="{{ url }}">Crate!</a>{% endblocktrans %}</p>
  {% endif %}

  {% if project.translations.exists %}
    <h3>{% trans "Translations" %}</h3>
      <ul>
      {% for trans in project.translations.all %}
          <li><a href="{{ trans.get_translation_url }}">{{ trans }}</a></li>
      {% endfor %}
      </ul>
  {% endif %}

  {% if project.subprojects.exists %}
    <h3>{% trans "Sub Projects" %}</h3>
      <ul>
      {% for rel in project.subprojects.all %}
          <li><a href="{{ rel.get_absolute_url }}">{{ rel.child }}</a></li>
      {% endfor %}
      </ul>
  {% endif %}

<h3>{% trans "Default Version" %}</h3>
<p> {{ project.get_default_version }}</p>

<h3>{% trans "'latest' version" %}</h3>
<p> {{ project.get_default_branch }}</p>

{% if request.user in project.users.all %}
  <h3>{% trans "Post Commit Hook" %}</h3>
    <p>
        curl -X POST http://{{ PRODUCTION_DOMAIN }}{% url generic_build project.pk %}
    </p>

{% endif %}

  {% if pageview_list %}
  <!-- BEGIN projects list -->
  <div class="module">
    <div class="module-wrapper">

      <div class="module-header">
        <h3>{% trans "Most viewed pages for this project" %}<span class="small_head"></span></h3>
      </div>

      <div class="module-list">
        <div class="module-list-wrapper">
          <ul>
          {% include "core/pageview_list_detailed.html" %}
          </ul>
        </div>
      </div>

    </div>
  </div>
  <!-- END projects list -->
  {% endif %}
</div>{# END .project_details #}

readthedocs/templates/core/version_list.html
<div class="module-list-wrapper">
  <ul>
  {% for version in filter %}
    <li class="module-item">
      {# Link to the docs #}
      <a class="module-item-title" href="{{ version.get_absolute_url }}">{{ version.slug }}</a>
      {% if request.user in project.users.all %}
        <span class="right-menu quiet">{{ version.get_privacy_level_display }}</span>
      {% endif %}
      {% if request.user in project.users.all %}
        <ul class="module-item-menu">
          <li><a href="{% url project_version_detail project.slug version.slug %}">{% trans "Add tags" %}</a></li>
        </ul>
      {% endif %}
    </li>
  {% endfor %}
  </ul>
</div>